name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Labeler
      uses: actions/labeler@v3-preview
      with:
        # The GITHUB_TOKEN secret
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

        # The path for the label configurations